"""Conversation management service for handling chat interactions and summaries."""

from pathlib import Path
from typing import Dict, List, Optional

import yaml

from assistant.core.interfaces.chat import IConversationService
from assistant.infrastructure.llm.openai_client import ChatCompletion
from assistant.services.chat_history import ChatHistory
from assistant.utils.markdown_sanitizer import sanitize_markdown_content


def load_translations(language_code: str) -> dict:
    """Load translations from YAML file for specified language."""
    try:
        translations_path = (
            Path(__file__).parent.parent.parent / "data" / "translations" / f"{language_code}.yml"
        )
        with open(translations_path, "r", encoding="utf-8") as f:
            return yaml.safe_load(f)
    except FileNotFoundError:
        print(f"Error: Translation file for {language_code} not found.")
        return {}
    except yaml.YAMLError:
        print(f"Error: Invalid YAML format in translation file for {language_code}.")
        return {}


class ConversationService(IConversationService):
    """Service for managing conversation state and generating summaries."""

    def __init__(self, max_history: int = 5, context_window: int = 3):
        """Initialize the conversation service."""
        self.chat_history = ChatHistory(max_history=max_history)
        self.context_window = context_window
        self.config = self._load_config()

    def get_service_name(self) -> str:
        """Return the unique service name."""
        return "ConversationService"

    def _load_config(self) -> dict:
        """Load configuration from YAML file."""
        try:
            config_path = Path(__file__).parent.parent.parent / "data" / "config.yml"
            with open(config_path, "r", encoding="utf-8") as f:
                return yaml.safe_load(f)
        except FileNotFoundError:
            print(f"Error: Config file not found.")
            return {}
        except yaml.YAMLError:
            print(f"Error: Invalid YAML format in config file.")
            return {}

    def add_interaction(
        self, user_message: str, assistant_response: str, category: Optional[str] = None
    ) -> None:
        """Add interaction to chat history."""
        self.chat_history.add_interaction(user_message, assistant_response, category)

    def get_context_messages(self) -> List[Dict[str, str]]:
        """Get recent interactions for context."""
        messages = []
        last_interactions = self.chat_history.get_last_n_interactions(self.context_window)
        for interaction in last_interactions:
            messages.extend(
                [
                    {"role": "user", "content": interaction.user_message},
                    {"role": "assistant", "content": interaction.assistant_response},
                ]
            )
        return messages

    def get_conversation_category(self) -> Optional[str]:
        """Get the current conversation category."""
        return self.chat_history.get_conversation_category()

    def set_conversation_category(self, category: str) -> None:
        """Set the conversation category."""
        self.chat_history.set_conversation_category(category)

    def clear_history(self) -> None:
        """Clear conversation history."""
        self.chat_history.clear_history()

    def handle_inappropriate_request(self, user_text: str) -> Dict[str, any]:
        """
        Handle inappropriate requests with polite redirection.

        Args:
            user_text: The user's inappropriate request

        Returns:
            Response dictionary with polite redirection
        """
        from assistant.agent.language_detection_agent import detect_language

        language = detect_language(user_text)

        responses = self.config.get("inappropriate_responses", {})
        if language == "cs":
            response = responses.get("czech", "Omlouvám se, nemohu vám s tím pomoci.")
        else:
            response = responses.get("english", "Sorry, I cannot help you with that.")

        self.add_interaction(user_text, response)
        return {"agent": True, "message": response, "prompt_category": "inappropriate_request"}

    async def generate_conversation_summary(self, user_message: str) -> str:
        """
        Generate a comprehensive summary of the full conversation using OpenAI.

        Args:
            user_message: The current user message

        Returns:
            Full conversation summary generated by OpenAI
        """
        try:
            # Get full conversation history
            interactions = self.chat_history.get_full_history()

            # Build conversation text with both user and assistant messages
            conversation_parts = []

            # Add chat history
            for interaction in interactions:
                if hasattr(interaction, "user_message") and hasattr(
                    interaction, "assistant_response"
                ):
                    conversation_parts.append(f"User: {interaction.user_message}")
                    conversation_parts.append(f"Assistant: {interaction.assistant_response}")

            # Add current message
            conversation_parts.append(f"User: {user_message}")

            conversation_text = "\n".join(conversation_parts)

            # Detect conversation language
            from assistant.agent.language_detection_agent import detect_language

            conversation_language = detect_language(
                user_message
                + " "
                + " ".join(
                    [
                        interaction.user_message
                        for interaction in interactions
                        if hasattr(interaction, "user_message")
                    ]
                )
            )

            # Create summarization prompt based on language
            if conversation_language == "cs":
                summarization_prompt = """Vytvoř stručné a informativní shrnutí této konverzace pro Luďka Kvapila. Zaměř se na:

1. Hlavní zájem či potřeby uživatele
2. Konkrétní služby nebo technologie, které zmínil
3. Důležité detaily o projektu nebo požadavcích
4. Kontaktní informace pokud byly poskytnuty

Shrnutí by mělo být v češtině, profesionální a obsahovat všechny podstatné informace pro následné kontaktování."""
            else:
                summarization_prompt = """Create a concise and informative summary of this conversation for Luděk Kvapil. Focus on:

1. The user's main interests or needs
2. Specific services or technologies mentioned
3. Important project details or requirements
4. Contact information if provided

The summary should be professional and contain all essential information for follow-up contact."""

            # Use OpenAI to generate summary
            messages = [
                {"role": "system", "content": summarization_prompt},
                {"role": "user", "content": f"Conversation to summarize:\n\n{conversation_text}"},
            ]

            chat = ChatCompletion(messages=messages, temperature=0.3, max_tokens=500)

            # Get the summary and sanitize any malformed markdown
            summary = await chat.get_response()
            sanitized_summary = sanitize_markdown_content(summary.strip())
            return sanitized_summary

        except Exception as e:
            print(f"Error generating AI summary: {str(e)}")
            # Fallback to simple summary
            return self._generate_simple_summary(user_message)

    def _generate_simple_summary(self, user_message: str) -> str:
        """
        Fallback method to generate a simple summary when OpenAI fails.
        Uses SummaryAgent for enhanced summary generation.
        """
        try:
            from assistant.agent.summary_agent import SummaryAgent

            interactions = self.chat_history.get_full_history()
            summary_agent = SummaryAgent()

            return summary_agent.generate_summary(user_message, interactions)

        except Exception as e:
            print(f"Error in simple summary: {str(e)}")
            return f"Conversation summary: {user_message[:100]}..."

    def check_greeting(self, user_text: str) -> Optional[Dict[str, any]]:
        """
        Check if message is a greeting and return appropriate response.

        Args:
            user_text: User's input text

        Returns:
            Response dict if greeting, None otherwise
        """
        user_text_lower = user_text.lower().strip()

        # Load greetings from config
        greetings_config = self.config.get("greetings", {})
        english_greetings = greetings_config.get("english", [])
        czech_greetings = greetings_config.get("czech", [])

        if user_text_lower in english_greetings:
            english_translations = load_translations("en")
            greeting_msg = english_translations.get("response_messages", {}).get(
                "greeting", "Hello! I'm here to help you."
            )
            self.add_interaction(user_text, greeting_msg)
            return {"agent": True, "message": greeting_msg, "prompt_category": "greeting"}
        elif user_text_lower in czech_greetings:
            czech_translations = load_translations("cs")
            greeting_msg = czech_translations.get("response_messages", {}).get(
                "greeting", "Ahoj! Jak vám můžu pomoci?"
            )
            self.add_interaction(user_text, greeting_msg)
            return {"agent": True, "message": greeting_msg, "prompt_category": "greeting"}

        return None

    def check_curiosity_response(self, user_text: str) -> Optional[Dict[str, any]]:
        """
        Check if user responded with curiosity to a technical question.

        Args:
            user_text: User's input text

        Returns:
            Response dict if curiosity detected, None otherwise
        """
        # Check for curiosity responses in technical context
        last_interactions = self.chat_history.get_last_n_interactions(1)
        if not last_interactions:
            return None

        last_response = last_interactions[0].assistant_response
        # Load conversation phrases from configuration
        czech_translations = load_translations("cs")
        english_translations = load_translations("en")
        czech_ask_phrases = czech_translations.get("conversation_phrases", {}).get(
            "ask_details_phrases", []
        )
        english_ask_phrases = english_translations.get("conversation_phrases", {}).get(
            "ask_details_phrases", []
        )
        all_ask_phrases = czech_ask_phrases + english_ask_phrases

        # Check if last response was asking for technical details
        was_asking_details = any(phrase in last_response.lower() for phrase in all_ask_phrases)

        # Check if current response shows curiosity
        from assistant.agent.language_detection_agent import detect_language

        language = detect_language(user_text)
        lang_code = "cs" if language == "cs" else "en"
        translations = load_translations(lang_code)
        curiosity_phrases = translations.get("summary_agent", {}).get("curiosity_phrases", [])
        is_curiosity_response = any(phrase in user_text.lower() for phrase in curiosity_phrases)

        if was_asking_details and is_curiosity_response:
            # User responded with curiosity to technical question - determine original category from last interaction
            # Get the conversation category that led to the ask_details
            last_interaction_category = last_interactions[0].category
            if last_interaction_category:
                print(
                    f"Curiosity response detected for {last_interaction_category} - providing technical answer"
                )
                return {
                    "agent": False,
                    "message": user_text,
                    "contexts": [],
                    "conversation_category": last_interaction_category,
                }
            else:
                # No category stored, but still treat as technical curiosity
                print("Curiosity response detected - providing general technical answer")
                return {
                    "agent": False,
                    "message": user_text,
                    "contexts": [],
                    "conversation_category": "curiosity_response",
                }

        return None
